[2025-06-22T11:07:40.653+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-22T11:07:40.671+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lf_recompute_bert_score.recompute_bert_scores manual__2025-06-22T11:07:32.893290+00:00 [queued]>
[2025-06-22T11:07:40.681+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lf_recompute_bert_score.recompute_bert_scores manual__2025-06-22T11:07:32.893290+00:00 [queued]>
[2025-06-22T11:07:40.682+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-22T11:07:40.699+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): recompute_bert_scores> on 2025-06-22 11:07:32.893290+00:00
[2025-06-22T11:07:40.709+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5385) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-22T11:07:40.712+0000] {standard_task_runner.py:63} INFO - Started process 5421 to run task
[2025-06-22T11:07:40.713+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'lf_recompute_bert_score', 'recompute_bert_scores', 'manual__2025-06-22T11:07:32.893290+00:00', '--job-id', '440', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpk4x14e7g']
[2025-06-22T11:07:40.718+0000] {standard_task_runner.py:91} INFO - Job 440: Subtask recompute_bert_scores
[2025-06-22T11:07:40.770+0000] {task_command.py:426} INFO - Running <TaskInstance: lf_recompute_bert_score.recompute_bert_scores manual__2025-06-22T11:07:32.893290+00:00 [running]> on host 5471b5a2dbbe
[2025-06-22T11:07:40.868+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lf_recompute_bert_score' AIRFLOW_CTX_TASK_ID='recompute_bert_scores' AIRFLOW_CTX_EXECUTION_DATE='2025-06-22T11:07:32.893290+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-22T11:07:32.893290+00:00'
[2025-06-22T11:07:40.870+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-22T11:07:40.889+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-22T11:07:40.890+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dags.py", line 330, in recompute_scores
    traces = lf.list_traces(name="SummaryWithBERTScore")
             ^^^^^^^^^^^^^^
AttributeError: 'Langfuse' object has no attribute 'list_traces'
[2025-06-22T11:07:40.904+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=lf_recompute_bert_score, task_id=recompute_bert_scores, run_id=manual__2025-06-22T11:07:32.893290+00:00, execution_date=20250622T110732, start_date=20250622T110740, end_date=20250622T110740
[2025-06-22T11:07:40.918+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 440 for task recompute_bert_scores ('Langfuse' object has no attribute 'list_traces'; 5421)
[2025-06-22T11:07:40.967+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-22T11:07:40.982+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-22T11:07:40.985+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
