[2025-06-22T11:04:38.298+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: deepai_crawler_10min.crawl_ml-research manual__2025-06-22T10:49:52.081134+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
