[2025-06-21T16:11:38.555+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: deepai_monthly_insights.generate_monthly_insights_per_collection manual__2025-06-21T16:11:34.898872+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
