[2025-05-04T17:46:17.911+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-04T17:46:17.937+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vietnamnet_crawler_24h.crawl_chinh-tri scheduled__2025-05-04T17:00:00+00:00 [queued]>
[2025-05-04T17:46:17.946+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vietnamnet_crawler_24h.crawl_chinh-tri scheduled__2025-05-04T17:00:00+00:00 [queued]>
[2025-05-04T17:46:17.947+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-05-04T17:46:17.963+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): crawl_chinh-tri> on 2025-05-04 17:00:00+00:00
[2025-05-04T17:46:17.970+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=200) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-04T17:46:17.973+0000] {standard_task_runner.py:63} INFO - Started process 203 to run task
[2025-05-04T17:46:17.972+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'vietnamnet_crawler_24h', 'crawl_chinh-tri', 'scheduled__2025-05-04T17:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpjfmhkr1w']
[2025-05-04T17:46:17.975+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask crawl_chinh-tri
[2025-05-04T17:46:18.031+0000] {task_command.py:426} INFO - Running <TaskInstance: vietnamnet_crawler_24h.crawl_chinh-tri scheduled__2025-05-04T17:00:00+00:00 [running]> on host 9f13ced5b14d
[2025-05-04T17:46:18.130+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vietnamnet_crawler_24h' AIRFLOW_CTX_TASK_ID='crawl_chinh-tri' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-04T17:00:00+00:00'
[2025-05-04T17:46:18.132+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-04T17:46:18.350+0000] {crawler.py:54} INFO - Đã kết nối thành công với MongoDB: News
[2025-05-04T17:46:18.514+0000] {crawler.py:44} INFO - ArticleSummarizer đã được khởi tạo thành công
[2025-05-04T17:46:18.595+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-04T17:46:18.596+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dags.py", line 72, in crawl_category
    asyncio.run(_crawl_category(category_url, category_name, max_articles, enable_summarizer))
  File "/home/airflow/.local/lib/python3.12/site-packages/nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dags.py", line 84, in _crawl_category
    await crawler.crawl_all_articles()
  File "/opt/airflow/dags/crawler.py", line 216, in crawl_all_articles
    article_links = await self.get_article_links()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawler.py", line 68, in get_article_links
    async with AsyncWebCrawler() as crawler:
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/crawl4ai/async_webcrawler.py", line 161, in __init__
    self.robots_parser = RobotsParser()
                         ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/crawl4ai/utils.py", line 224, in __init__
    self._init_db()
  File "/home/airflow/.local/lib/python3.12/site-packages/crawl4ai/utils.py", line 229, in _init_db
    conn.execute("PRAGMA journal_mode=WAL")
sqlite3.OperationalError: database is locked
[2025-05-04T17:46:18.614+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=vietnamnet_crawler_24h, task_id=crawl_chinh-tri, run_id=scheduled__2025-05-04T17:00:00+00:00, execution_date=20250504T170000, start_date=20250504T174617, end_date=20250504T174618
[2025-05-04T17:46:18.632+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task crawl_chinh-tri (database is locked; 203)
[2025-05-04T17:46:18.668+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-04T17:46:18.696+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-04T17:46:18.698+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
