[2025-06-22T12:00:57.110+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-22T12:00:57.140+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deepai_crawler_10min.crawl_data-points scheduled__2025-06-22T11:50:00+00:00 [queued]>
[2025-06-22T12:00:57.160+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deepai_crawler_10min.crawl_data-points scheduled__2025-06-22T11:50:00+00:00 [queued]>
[2025-06-22T12:00:57.161+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-06-22T12:00:57.182+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): crawl_data-points> on 2025-06-22 11:50:00+00:00
[2025-06-22T12:00:57.196+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=15961) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-22T12:00:57.200+0000] {standard_task_runner.py:63} INFO - Started process 16017 to run task
[2025-06-22T12:00:57.202+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'deepai_crawler_10min', 'crawl_data-points', 'scheduled__2025-06-22T11:50:00+00:00', '--job-id', '509', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp85v2m91r']
[2025-06-22T12:00:57.208+0000] {standard_task_runner.py:91} INFO - Job 509: Subtask crawl_data-points
[2025-06-22T12:00:57.296+0000] {task_command.py:426} INFO - Running <TaskInstance: deepai_crawler_10min.crawl_data-points scheduled__2025-06-22T11:50:00+00:00 [running]> on host 5471b5a2dbbe
[2025-06-22T12:00:57.498+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deepai_crawler_10min' AIRFLOW_CTX_TASK_ID='crawl_data-points' AIRFLOW_CTX_EXECUTION_DATE='2025-06-22T11:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-22T11:50:00+00:00'
[2025-06-22T12:00:57.500+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-22T12:00:57.526+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-22T12:00:57.527+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: crawl_deepai_category() missing 5 required positional arguments: 'category_url', 'category_name', 'max_articles', 'min_articles_threshold', and 'max_load_more_clicks'
[2025-06-22T12:00:57.547+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=deepai_crawler_10min, task_id=crawl_data-points, run_id=scheduled__2025-06-22T11:50:00+00:00, execution_date=20250622T115000, start_date=20250622T120057, end_date=20250622T120057
[2025-06-22T12:00:57.577+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 509 for task crawl_data-points (crawl_deepai_category() missing 5 required positional arguments: 'category_url', 'category_name', 'max_articles', 'min_articles_threshold', and 'max_load_more_clicks'; 16017)
[2025-06-22T12:00:57.617+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-22T12:00:57.634+0000] {media_manager.py:52} DEBUG - Queue: Media upload queue is empty, waiting for new jobs
[2025-06-22T12:00:57.684+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-22T12:00:57.689+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
