[2025-06-22T11:13:53.222+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-22T11:13:53.241+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lf_recompute_bert_score.recompute_bert_scores manual__2025-06-22T11:08:38.426819+00:00 [queued]>
[2025-06-22T11:13:53.250+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lf_recompute_bert_score.recompute_bert_scores manual__2025-06-22T11:08:38.426819+00:00 [queued]>
[2025-06-22T11:13:53.251+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-22T11:13:53.269+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): recompute_bert_scores> on 2025-06-22 11:08:38.426819+00:00
[2025-06-22T11:13:53.280+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7237) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-22T11:13:53.282+0000] {standard_task_runner.py:63} INFO - Started process 7255 to run task
[2025-06-22T11:13:53.285+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'lf_recompute_bert_score', 'recompute_bert_scores', 'manual__2025-06-22T11:08:38.426819+00:00', '--job-id', '457', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp5p7rnkso']
[2025-06-22T11:13:53.289+0000] {standard_task_runner.py:91} INFO - Job 457: Subtask recompute_bert_scores
[2025-06-22T11:13:53.341+0000] {task_command.py:426} INFO - Running <TaskInstance: lf_recompute_bert_score.recompute_bert_scores manual__2025-06-22T11:08:38.426819+00:00 [running]> on host 5471b5a2dbbe
[2025-06-22T11:13:53.438+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lf_recompute_bert_score' AIRFLOW_CTX_TASK_ID='recompute_bert_scores' AIRFLOW_CTX_EXECUTION_DATE='2025-06-22T11:08:38.426819+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-22T11:08:38.426819+00:00'
[2025-06-22T11:13:53.439+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-22T11:13:53.457+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-22T11:13:53.458+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dags.py", line 329, in recompute_scores
    traces = lf.traces.list(name="SummaryWithBERTScore")
             ^^^^^^^^^
AttributeError: 'Langfuse' object has no attribute 'traces'
[2025-06-22T11:13:53.469+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=lf_recompute_bert_score, task_id=recompute_bert_scores, run_id=manual__2025-06-22T11:08:38.426819+00:00, execution_date=20250622T110838, start_date=20250622T111353, end_date=20250622T111353
[2025-06-22T11:13:53.484+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 457 for task recompute_bert_scores ('Langfuse' object has no attribute 'traces'; 7255)
[2025-06-22T11:13:53.497+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-22T11:13:53.513+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-22T11:13:53.516+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
