[2025-06-08T20:24:07.414+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T20:24:07.433+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deepai_monthly_insights.generate_monthly_insights_per_collection manual__2025-06-08T20:02:53.532370+00:00 [queued]>
[2025-06-08T20:24:07.442+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deepai_monthly_insights.generate_monthly_insights_per_collection manual__2025-06-08T20:02:53.532370+00:00 [queued]>
[2025-06-08T20:24:07.442+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-06-08T20:24:07.463+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_monthly_insights_per_collection> on 2025-06-08 20:02:53.532370+00:00
[2025-06-08T20:24:07.470+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=147) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-08T20:24:07.472+0000] {standard_task_runner.py:63} INFO - Started process 153 to run task
[2025-06-08T20:24:07.473+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'deepai_monthly_insights', 'generate_monthly_insights_per_collection', 'manual__2025-06-08T20:02:53.532370+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpriuyz77o']
[2025-06-08T20:24:07.475+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask generate_monthly_insights_per_collection
[2025-06-08T20:24:07.525+0000] {task_command.py:426} INFO - Running <TaskInstance: deepai_monthly_insights.generate_monthly_insights_per_collection manual__2025-06-08T20:02:53.532370+00:00 [running]> on host 9066188fa759
[2025-06-08T20:24:07.614+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deepai_monthly_insights' AIRFLOW_CTX_TASK_ID='generate_monthly_insights_per_collection' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T20:02:53.532370+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T20:02:53.532370+00:00'
[2025-06-08T20:24:07.618+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T20:24:07.639+0000] {dags.py:199} INFO - Báº¯t Ä‘áº§u táº¡o insights cho tá»«ng category tá»« dá»¯ liá»‡u thÃ¡ng qua
[2025-06-08T20:24:08.053+0000] {dags.py:213} INFO - Táº¡o insights riÃªng cho tá»«ng category vÃ  lÆ°u vÃ o database...
[2025-06-08T20:24:08.920+0000] {dags.py:233} ERROR - Lá»—i khi táº¡o insights: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - '/home/***/nltk_data'
    - '/home/***/.local/nltk_data'
    - '/home/***/.local/share/nltk_data'
    - '/home/***/.local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

[2025-06-08T20:24:08.920+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T20:24:08.921+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dags.py", line 214, in generate_monthly_insights
    saved_count = summarizer.save_insights_to_db(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/deeplearning_ai/Insight.py", line 171, in save_insights_to_db
    insights = self.summarize_each_collection(k=k, max_tokens=max_tokens, return_prompt_only=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/deeplearning_ai/Insight.py", line 140, in summarize_each_collection
    item["tokens"] = self.count_tokens(item.get("summary", ""))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/deeplearning_ai/Insight.py", line 20, in count_tokens
    return len(word_tokenize(text))
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/tokenize/__init__.py", line 142, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/tokenize/__init__.py", line 119, in sent_tokenize
    tokenizer = _get_punkt_tokenizer(language)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/tokenize/__init__.py", line 105, in _get_punkt_tokenizer
    return PunktTokenizer(language)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/tokenize/punkt.py", line 1744, in __init__
    self.load_lang(lang)
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/tokenize/punkt.py", line 1749, in load_lang
    lang_dir = find(f"tokenizers/punkt_tab/{lang}/")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - '/home/***/nltk_data'
    - '/home/***/.local/nltk_data'
    - '/home/***/.local/share/nltk_data'
    - '/home/***/.local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

[2025-06-08T20:24:08.930+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=deepai_monthly_insights, task_id=generate_monthly_insights_per_collection, run_id=manual__2025-06-08T20:02:53.532370+00:00, execution_date=20250608T200253, start_date=20250608T202407, end_date=20250608T202408
[2025-06-08T20:24:08.941+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task generate_monthly_insights_per_collection (
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - '/home/***/nltk_data'
    - '/home/***/.local/nltk_data'
    - '/home/***/.local/share/nltk_data'
    - '/home/***/.local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
; 153)
[2025-06-08T20:24:08.972+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-08T20:24:08.986+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-08T20:24:08.989+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
